import React, { useState } from 'react';
import jsPDF from 'jspdf';
import { 
  X, ShieldCheck, CreditCard, QrCode, Building2, 
  CheckCircle2, Download, Mail, Loader2, ArrowRight, User, Globe
} from 'lucide-react';

export default function BookingPaymentModal({ isOpen, onClose, bookingDetails }) {
  // Fallback defaults if props aren't passed
  const details = bookingDetails || {
    expeditionName: 'Antarctic Peninsula Odyssey',
    duration: '11 Days • Departs: Ushuaia, Argentina',
    passengers: 1,
    cabinClass: 'Standard Suite',
    totalAmount: 8950,
  };

  const [step, setStep] = useState('payment'); // 'payment' | 'processing' | 'success'
  const [paymentMethod, setPaymentMethod] = useState('card');
  const [isSendingEmail, setIsSendingEmail] = useState(false);
  const [emailSent, setEmailSent] = useState(false);

  // Form State
  const [formData, setFormData] = useState({
    fullName: 'Alex Vance',
    email: 'alex.vance@example.com',
    cardNumber: '•••• •••• •••• 4242',
    cardExp: '12/28',
    cardCvc: '888',
    upiId: 'alex@upi',
    bank: 'HDFC Bank',
  });

  if (!isOpen) return null;

  const handleInputChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // Automated PDF Ticket Generator
  const generatePDFTicket = (bookingId) => {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Dark Header Banner
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 40, 'F');

    // Branding / Header Text
    doc.setTextColor(6, 182, 212); // cyan-500
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('POLAR EXPEDITIONS PASS', 15, 20);

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`BOOKING REF: #${bookingId}`, 15, 30);
    doc.text(`ISSUED: ${new Date().toLocaleDateString()}`, 145, 30);

    // Expedition Title Section
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(details.expeditionName, 15, 55);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(details.duration, 15, 62);

    // Separator line
    doc.setDrawColor(226, 232, 240);
    doc.line(15, 68, 195, 68);

    // Passenger & Ticket Details Table
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    
    // Column 1
    doc.setFont('helvetica', 'bold');
    doc.text('Passenger Name:', 15, 80);
    doc.setFont('helvetica', 'normal');
    doc.text(formData.fullName, 60, 80);

    doc.setFont('helvetica', 'bold');
    doc.text('Email Address:', 15, 90);
    doc.setFont('helvetica', 'normal');
    doc.text(formData.email, 60, 90);

    doc.setFont('helvetica', 'bold');
    doc.text('Cabin Category:', 15, 100);
    doc.setFont('helvetica', 'normal');
    doc.text(details.cabinClass, 60, 100);

    // Column 2
    doc.setFont('helvetica', 'bold');
    doc.text('Guests / Seats:', 120, 80);
    doc.setFont('helvetica', 'normal');
    doc.text(`${details.passengers} Guest(s)`, 160, 80);

    doc.setFont('helvetica', 'bold');
    doc.text('Payment Status:', 120, 90);
    doc.setTextColor(16, 185, 129); // Green
    doc.text('CONFIRMED / PAID', 160, 90);

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Total Paid:', 120, 100);
    doc.setFont('helvetica', 'normal');
    doc.text(`$${details.totalAmount.toLocaleString()} USD`, 160, 100);

    // Instructions Box
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(15, 115, 180, 35, 3, 3, 'F');
    
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);
    doc.setFont('helvetica', 'bold');
    doc.text('IMPORTANT EMBARKATION INFORMATION:', 20, 123);
    doc.setFont('helvetica', 'normal');
    doc.text('• Please present this boarding pass along with your valid passport upon embarkation at Ushuaia Port.', 20, 130);
    doc.text('• Medical clearance and polar gear verification must be completed 24 hours prior to departure.', 20, 136);

    // Footer Stamp
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Automated electronic ticket generated by Polar Expeditions API.', 15, 280);

    return doc;
  };

  // Handle Submit & Payment Processing Simulation
  const handlePaymentSubmit = (e) => {
    e.preventDefault();
    setStep('processing');

    setTimeout(() => {
      const bookingId = 'ANT-' + Math.floor(100000 + Math.random() * 900000);
      const pdf = generatePDFTicket(bookingId);
      
      // Auto Download
      pdf.save(`Boarding_Pass_${bookingId}.pdf`);

      setStep('success');
      setEmailSent(true);
    }, 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="relative w-full max-w-xl overflow-hidden border rounded-2xl bg-slate-900 border-slate-800 text-slate-100 shadow-2xl">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/50">
          <div>
            <h2 className="text-lg font-bold text-white">Complete Booking & Checkout</h2>
            <p className="text-xs text-slate-400">{details.expeditionName}</p>
          </div>
          <button 
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Step 1: Payment Selection Form */}
        {step === 'payment' && (
          <form onSubmit={handlePaymentSubmit} className="p-6 space-y-5">
            {/* Passenger Information */}
            <div className="space-y-3">
              <label className="text-xs font-semibold tracking-wider uppercase text-slate-400">
                Primary Passenger Details
              </label>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="relative">
                  <User className="absolute left-3 top-3 w-4 h-4 text-slate-500" />
                  <input
                    type="text"
                    name="fullName"
                    required
                    value={formData.fullName}
                    onChange={handleInputChange}
                    placeholder="Full Name"
                    className="w-full pl-9 pr-3 py-2 text-sm bg-slate-800/80 border border-slate-700 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  />
                </div>
                <div className="relative">
                  <Mail className="absolute left-3 top-3 w-4 h-4 text-slate-500" />
                  <input
                    type="email"
                    name="email"
                    required
                    value={formData.email}
                    onChange={handleInputChange}
                    placeholder="Email for Tickets"
                    className="w-full pl-9 pr-3 py-2 text-sm bg-slate-800/80 border border-slate-700 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  />
                </div>
              </div>
            </div>

            {/* Payment Method Selector Tabs */}
            <div className="space-y-2">
              <label className="text-xs font-semibold tracking-wider uppercase text-slate-400">
                Select Payment Method
              </label>
              <div className="grid grid-cols-3 gap-2">
                <button
                  type="button"
                  onClick={() => setPaymentMethod('card')}
                  className={`flex items-center justify-center gap-2 p-2.5 text-xs font-medium rounded-lg border transition ${
                    paymentMethod === 'card'
                      ? 'bg-cyan-500/10 border-cyan-500 text-cyan-400'
                      : 'bg-slate-800/50 border-slate-700 text-slate-300 hover:bg-slate-800'
                  }`}
                >
                  <CreditCard className="w-4 h-4" /> Card
                </button>
                <button
                  type="button"
                  onClick={() => setPaymentMethod('upi')}
                  className={`flex items-center justify-center gap-2 p-2.5 text-xs font-medium rounded-lg border transition ${
                    paymentMethod === 'upi'
                      ? 'bg-cyan-500/10 border-cyan-500 text-cyan-400'
                      : 'bg-slate-800/50 border-slate-700 text-slate-300 hover:bg-slate-800'
                  }`}
                >
                  <QrCode className="w-4 h-4" /> UPI / QR
                </button>
                <button
                  type="button"
                  onClick={() => setPaymentMethod('netbanking')}
                  className={`flex items-center justify-center gap-2 p-2.5 text-xs font-medium rounded-lg border transition ${
                    paymentMethod === 'netbanking'
                      ? 'bg-cyan-500/10 border-cyan-500 text-cyan-400'
                      : 'bg-slate-800/50 border-slate-700 text-slate-300 hover:bg-slate-800'
                  }`}
                >
                  <Building2 className="w-4 h-4" /> NetBanking
                </button>
              </div>
            </div>

            {/* Dynamic Payment Option Forms */}
            <div className="p-4 rounded-xl bg-slate-950/40 border border-slate-800">
              {paymentMethod === 'card' && (
                <div className="space-y-3">
                  <input
                    type="text"
                    name="cardNumber"
                    value={formData.cardNumber}
                    onChange={handleInputChange}
                    placeholder="Card Number"
                    className="w-full px-3 py-2 text-sm bg-slate-800 border border-slate-700 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  />
                  <div className="grid grid-cols-2 gap-2">
                    <input
                      type="text"
                      name="cardExp"
                      value={formData.cardExp}
                      onChange={handleInputChange}
                      placeholder="MM/YY"
                      className="px-3 py-2 text-sm bg-slate-800 border border-slate-700 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                    />
                    <input
                      type="text"
                      name="cardCvc"
                      value={formData.cardCvc}
                      onChange={handleInputChange}
                      placeholder="CVC"
                      className="px-3 py-2 text-sm bg-slate-800 border border-slate-700 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                    />
                  </div>
                </div>
              )}

              {paymentMethod === 'upi' && (
                <div className="text-center space-y-3">
                  <p className="text-xs text-slate-400">Scan QR or enter VPA ID to pay instantly</p>
                  <div className="inline-block p-2 bg-white rounded-lg">
                    {/* Simulated QR Code placeholder */}
                    <div className="w-28 h-28 bg-slate-900 rounded flex items-center justify-center text-[10px] text-cyan-400 font-mono">
                      [ SCAN QR CODE ]
                    </div>
                  </div>
                  <input
                    type="text"
                    name="upiId"
                    value={formData.upiId}
                    onChange={handleInputChange}
                    placeholder="username@upi"
                    className="w-full px-3 py-2 text-sm bg-slate-800 border border-slate-700 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  />
                </div>
              )}

              {paymentMethod === 'netbanking' && (
                <div className="space-y-2">
                  <label className="text-xs text-slate-400">Select Bank</label>
                  <select 
                    name="bank"
                    value={formData.bank}
                    onChange={handleInputChange}
                    className="w-full px-3 py-2 text-sm bg-slate-800 border border-slate-700 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  >
                    <option value="HDFC Bank">HDFC Bank</option>
                    <option value="State Bank of India">State Bank of India</option>
                    <option value="ICICI Bank">ICICI Bank</option>
                    <option value="Axis Bank">Axis Bank</option>
                  </select>
                </div>
              )}
            </div>

            {/* Total & Submit Button */}
            <div className="flex items-center justify-between pt-2 border-t border-slate-800">
              <div>
                <p className="text-xs text-slate-400">Total Payable Amount</p>
                <p className="text-xl font-bold text-cyan-400">${details.totalAmount.toLocaleString()} USD</p>
              </div>
              <button
                type="submit"
                className="flex items-center gap-2 px-6 py-2.5 font-semibold text-slate-950 bg-cyan-400 hover:bg-cyan-300 rounded-xl shadow-lg shadow-cyan-500/20 transition"
              >
                Pay & Generate Ticket <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </form>
        )}

        {/* Step 2: Processing Screen */}
        {step === 'processing' && (
          <div className="py-16 text-center space-y-4">
            <Loader2 className="w-12 h-12 text-cyan-400 animate-spin mx-auto" />
            <div>
              <h3 className="text-lg font-semibold text-white">Processing Payment...</h3>
              <p className="text-xs text-slate-400">Securing your cabin booking & generating PDF pass</p>
            </div>
          </div>
        )}

        {/* Step 3: Success Screen */}
        {step === 'success' && (
          <div className="p-8 text-center space-y-5">
            <div className="w-14 h-14 bg-emerald-500/10 border border-emerald-500/30 rounded-full flex items-center justify-center mx-auto text-emerald-400">
              <CheckCircle2 className="w-8 h-8" />
            </div>

            <div>
              <h3 className="text-xl font-bold text-white">Booking Confirmed!</h3>
              <p className="text-sm text-slate-400 mt-1">
                Your PDF boarding ticket has been automatically downloaded.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800 text-left space-y-2">
              <div className="flex items-center gap-2 text-xs text-slate-300">
                <Mail className="w-4 h-4 text-cyan-400" />
                <span>Automated email dispatched to: <strong>{formData.email}</strong></span>
              </div>
              <div className="flex items-center gap-2 text-xs text-slate-300">
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>Verification QR Code embedded in generated PDF ticket</span>
              </div>
            </div>

            <div className="flex gap-3 justify-center pt-2">
              <button
                onClick={onClose}
                className="px-6 py-2.5 text-sm font-semibold bg-slate-800 hover:bg-slate-700 text-white rounded-xl transition"
              >
                Done / Close
              </button>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}